create table if not exists public.app_documents (
  id bigint generated by default as identity primary key,
  collection text not null,
  doc_id text not null,
  email text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(collection, doc_id)
);

create index if not exists app_documents_collection_idx on public.app_documents (collection);
create index if not exists app_documents_collection_email_idx on public.app_documents (collection, email);
create index if not exists app_documents_updated_at_idx on public.app_documents (updated_at desc);
