-- Zavora server document storage for auth, sessions, dashboard data and affiliate data.
-- Run this in Supabase SQL Editor with the Primary Database selected.
-- If Supabase shows ECONNREFUSED, the database is unavailable/paused; resume it and run again.

create table if not exists public.app_documents (
  id bigint generated by default as identity primary key,
  collection text not null,
  doc_id text not null,
  email text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(collection, doc_id)
);

alter table public.app_documents add column if not exists collection text;
alter table public.app_documents add column if not exists doc_id text;
alter table public.app_documents add column if not exists email text;
alter table public.app_documents add column if not exists payload jsonb not null default '{}'::jsonb;
alter table public.app_documents add column if not exists created_at timestamptz not null default now();
alter table public.app_documents add column if not exists updated_at timestamptz not null default now();

create index if not exists app_documents_collection_idx on public.app_documents (collection);
create index if not exists app_documents_collection_email_idx on public.app_documents (collection, email);
create index if not exists app_documents_updated_at_idx on public.app_documents (updated_at desc);
create unique index if not exists app_documents_collection_doc_id_uidx on public.app_documents (collection, doc_id);

create or replace function public.set_app_documents_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists app_documents_updated_at on public.app_documents;
create trigger app_documents_updated_at
before update on public.app_documents
for each row
execute function public.set_app_documents_updated_at();

-- Authentication documents contain password hashes, OTPs and session-related data.
-- Only the server-side secret/service-role key may access this table.
revoke all on public.app_documents from anon, authenticated;
revoke all on sequence public.app_documents_id_seq from anon, authenticated;
grant usage on schema public to service_role;
grant select, insert, update, delete on public.app_documents to service_role;
grant usage, select on sequence public.app_documents_id_seq to service_role;

alter table public.app_documents enable row level security;

notify pgrst, 'reload schema';

select to_regclass('public.app_documents') as app_documents_table;
select column_name, data_type, is_nullable
from information_schema.columns
where table_schema = 'public' and table_name = 'app_documents'
order by ordinal_position;
