create table if not exists public.products (
  id bigint generated by default as identity primary key,
  printful_id text not null unique,
  store_product_id text,
  name text not null,
  gender text,
  category text,
  category_path text,
  product_type text,
  collection text[] default '{}',
  color text,
  colors text[] default '{}',
  sizes text[] default '{}',
  price numeric,
  compare_at numeric,
  image text,
  images jsonb default '[]'::jsonb,
  variant_groups jsonb default '{}'::jsonb,
  variants jsonb default '[]'::jsonb,
  payload jsonb not null,
  source text default 'printful',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists products_category_idx on public.products (category);
create index if not exists products_gender_idx on public.products (gender);
create index if not exists products_collection_gin_idx on public.products using gin (collection);
